import fs from 'node:fs/promises';
import path from 'node:path';
import assert from 'node:assert/strict';
import {openApp,ready,loadNative,saveDownload,dropSample,E} from './browser_common.mjs';
const app=await openApp(),{page}=app,scenarios=[];
const pass=name=>{scenarios.push(name);console.log('PASS '+name);};
async function error(){await page.waitForFunction(()=>document.body.dataset.state==='error');assert.equal(await page.locator('#download').isDisabled(),true);assert.equal(await page.locator('#workbench').isHidden(),true);}
try{
 assert.equal(await page.locator('html').getAttribute('lang'),'ja');await page.keyboard.press('Tab');assert.equal(await page.locator('.skip').evaluate(n=>n===document.activeElement),true);await page.keyboard.press('Enter');assert.equal(await page.locator('#main').evaluate(n=>n===document.activeElement),true);pass('Japanese default and keyboard skip link');
 await page.locator('#sample').focus();await page.keyboard.press('Enter');await ready(page);assert.equal(await page.locator('#document-count').textContent(),'6');assert.equal(await page.locator('#download').isDisabled(),true);assert.equal(await page.locator('#mapping-rows tr').count(),6);pass('Keyboard sample retains one row per complete source document');
 await page.locator('#lang-en').click();await page.locator('#ack').focus();await page.keyboard.press('Space');assert.equal(await page.locator('#download').isDisabled(),false);await saveDownload(page,'#download','ui-keyboard-copy.zip');pass('Keyboard acknowledgment enables a real browser ZIP download');
 await saveDownload(page,'#download','ui-repeat-copy.zip');assert.deepEqual(await fs.readFile(path.join(E,'ui-keyboard-copy.zip')),await fs.readFile(path.join(E,'ui-repeat-copy.zip')));pass('Repeated export produces the same complete ZIP without accumulating entries');
 await page.locator('#sample').click();await ready(page);assert.equal(await page.locator('#ack').isChecked(),false);assert.equal(await page.locator('#download').isDisabled(),true);pass('Repeated input clears prior acknowledgment');
 await page.locator('#select-none').click();assert.equal(await page.locator('#selected-count').textContent(),'0');await page.locator('#ack').check();assert.equal(await page.locator('#download').isDisabled(),true);await page.locator('#select-all').click();assert.equal(await page.locator('#ack').isChecked(),false);pass('Empty selection blocks output and selecting again resets acknowledgment');
 await loadNative(page);assert.equal(await page.locator('#document-count').textContent(),'8');assert.equal(await page.locator('#directory-count').textContent(),'8');assert.equal(await page.locator('#count-archive').textContent(),'(1)');assert.equal(await page.locator('#count-trash').textContent(),'(1)');pass('Real folder input loads the native fixture with Archive and Trash bodies');
 await page.locator('#ack').check();await loadNative(page);assert.equal(await page.locator('#ack').isChecked(),false);pass('Repeated native folder input cannot reuse review approval');
 await page.locator('#group-inactive').uncheck();await page.locator('#group-archive').uncheck();await page.locator('#group-trash').uncheck();assert.equal(await page.locator('#selected-count').textContent(),'5');assert.equal(await page.locator('#mapping-rows tr.excluded').count(),3);await saveDownload(page,'#report','ui-unacknowledged-selection.json');const report=JSON.parse(await fs.readFile(path.join(E,'ui-unacknowledged-selection.json'),'utf8'));assert.equal(report.selection.acknowledged,false);assert.equal(report.selection.excludedHandles.length,3);assert.equal(report.items.length,15);pass('Inactive, Archive and Trash exclusions are explicit and retained in the review');
 await page.locator('#select-all').click();const first=page.locator('#tree button').first();await first.focus();await page.keyboard.press('ArrowDown');assert.equal(await page.locator('#preview-heading').textContent(),'Part α');await page.keyboard.press('End');assert.equal(await page.locator('#preview-heading').textContent(),'Discarded');assert.match(await page.locator('#body-preview').textContent(),/Trash text is still source text/);await page.keyboard.press('Home');assert.equal(await page.locator('#preview-heading').textContent(),'Novel');pass('Tree preview has keyboard arrow, Home and End navigation');
 await dropSample(page,{xmlReplace:['>Duplicate<','>../CON:雪?<']});await ready(page);assert.ok(await page.locator('.adjusted').count()>0);const paths=await page.locator('td.path').allTextContents();assert.ok(paths.some(p=>p.includes('_CON_雪_')));assert.ok(paths.every(p=>!p.split('/').includes('..')));await page.locator('#ack').check();await saveDownload(page,'#download','ui-safe-filenames.zip');pass('Unsafe label mapping is visible and exported paths stay inside the tree');
 await dropSample(page,{body:'<img src="https://example.invalid/should-not-load"><script>window.__executed=true</script>\n'});await ready(page);assert.equal(await page.locator('#body-preview img').count(),0);assert.equal(await page.evaluate(()=>window.__executed),undefined);assert.match(await page.locator('#body-preview').textContent(),/<script>/);pass('Source HTML/script-looking text is displayed literally without execution or network');
 await dropSample(page,{xmlReplace:['fileVersion="1.6"','fileVersion="1.5"']});await error();assert.match(await page.locator('#error').textContent(),/1.6 revision 0/);await page.locator('#lang-ja').click();assert.match(await page.locator('#error').textContent(),/だけが対象/);pass('Unsupported format rejects stale output and error language changes');
 await dropSample(page,{xmlReplace:['<settings>','<!DOCTYPE x [<!ENTITY x "danger">]><settings>']});await error();pass('Entity/DOCTYPE input is rejected');
 await page.evaluate(()=>{const data=new DataTransfer(),source=globalThis.DraftShelfSample;let skipped=false;for(const [name,text]of Object.entries(source)){if(name.endsWith('.md')&&!skipped){skipped=true;continue;}data.items.add(new File([text],name.split('/').at(-1)));}document.getElementById('drop-zone').dispatchEvent(new DragEvent('drop',{dataTransfer:data,bubbles:true}));});await error();pass('Missing referenced body blocks the entire export');
 await page.evaluate(()=>{window.__oversizeRead=false;const f=new File([new Uint8Array(2097153)],'nwProject.nwx');Object.defineProperty(f,'arrayBuffer',{value:()=>{window.__oversizeRead=true;return Promise.resolve(new ArrayBuffer(0));}});const d=new DataTransfer();d.items.add(f);document.getElementById('drop-zone').dispatchEvent(new DragEvent('drop',{dataTransfer:d,bubbles:true}));});await error();assert.equal(await page.evaluate(()=>window.__oversizeRead),false);pass('File size is bounded before byte reading');
 for(const suppliedPath of ['../nwProject.nwx','C:/project/nwProject.nwx']){await page.evaluate(p=>{const d=new DataTransfer(),f=new File(['x'],'nwProject.nwx');Object.defineProperty(f,'webkitRelativePath',{value:p});d.items.add(f);document.getElementById('drop-zone').dispatchEvent(new DragEvent('drop',{dataTransfer:d,bubbles:true}));},suppliedPath);await error();}pass('Supplied traversal and drive-qualified paths are rejected without filesystem access');
 await page.evaluate(()=>{const original=File.prototype.arrayBuffer;File.prototype.arrayBuffer=async function(){if(this._testDelay){window.__delayedStarted=true;await new Promise(resolve=>setTimeout(resolve,this._testDelay));}return original.call(this);};window.__delayedStarted=false;});
 await dropSample(page,{xmlReplace:['DraftShelf Native Fixture','Older project'],delay:250});await page.waitForFunction(()=>window.__delayedStarted);await page.locator('#sample').click();await ready(page);await page.waitForTimeout(350);assert.notEqual(await page.locator('#project-title').textContent(),'Older project');assert.equal(await page.locator('#document-count').textContent(),'6');pass('A newer file selection wins over an older asynchronous completion');
 await page.evaluate(()=>window.__delayedStarted=false);await dropSample(page,{delay:250});await page.waitForFunction(()=>window.__delayedStarted);await page.locator('#clear').click();await page.waitForTimeout(350);assert.equal(await page.evaluate(()=>document.body.dataset.state),'empty');assert.equal(await page.locator('#workbench').isHidden(),true);assert.equal(await page.locator('#project-title').textContent(),'');assert.equal(await page.locator('#body-preview').textContent(),'');pass('Clear cancels pending reads without resurrecting source data');
 await page.evaluate(()=>{const input=document.getElementById('file-input');input.value='';input.dispatchEvent(new Event('change',{bubbles:true}));});assert.equal(await page.evaluate(()=>document.body.dataset.state),'empty');pass('Explicit empty-change event leaves no stale review (not OS-picker cancellation)');
 await loadNative(page);await page.locator('#lang-en').click();await page.screenshot({path:path.join(E,'ui-en-desktop.png'),fullPage:true});await page.locator('#lang-ja').click();await page.screenshot({path:path.join(E,'ui-ja-desktop.png'),fullPage:true});
 await page.setViewportSize({width:390,height:844});await page.screenshot({path:path.join(E,'ui-ja-mobile.png'),fullPage:true});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await page.locator('#lang-en').click();await page.screenshot({path:path.join(E,'ui-en-mobile.png'),fullPage:true});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await page.locator('.table-scroll').evaluate(n=>n.scrollLeft=n.scrollWidth);const edge=await page.locator('.table-scroll').evaluate(n=>{const box=n.getBoundingClientRect(),cell=n.querySelector('thead th:last-child').getBoundingClientRect();return {left:box.left,right:box.right,cellLeft:cell.left,cellRight:cell.right,overflow:n.scrollWidth>n.clientWidth};});assert.equal(edge.overflow,true);assert.ok(edge.cellLeft>=edge.left-1&&edge.cellRight<=edge.right+1,'Rightmost column must be completely visible after horizontal scroll');await page.screenshot({path:path.join(E,'ui-en-mobile-table-end.png'),fullPage:true});pass('JA/EN desktop and 390px mobile preserve all rows and expose the complete rightmost table column');
 await page.setViewportSize({width:1440,height:1040});await page.emulateMedia({media:'print'});assert.equal(await page.locator('#mapping-rows tr').count(),8);await page.screenshot({path:path.join(E,'ui-print.png'),fullPage:true});await page.pdf({path:path.join(E,'ui-print.pdf'),format:'A4',landscape:true,printBackground:true});await page.emulateMedia({media:'screen'});pass('Print review retains every mapping row and explicit omission/backup limits');
 assert.deepEqual(app.errors,[]);assert.deepEqual(app.network,[]);pass('Packaged file-protocol app has no console errors or HTTP requests');
 await fs.writeFile(path.join(E,'browser-ui-result.json'),JSON.stringify({status:'pass',scenarios,consoleErrors:app.errors,networkRequests:app.network},null,2)+'\n');
}catch(error){await page.screenshot({path:path.join(E,'FAILED-browser-test.png'),fullPage:true});throw error;}finally{await app.browser.close();}
